-  # **PART - 1. ARTIFICIAL NEURAL NETWORK:**


# **Importing the libraries:**

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import sklearn as sk
import tensorflow as tf    # Deep learning library:

# **Now check the version of tensorflow:**

In [2]:
tf.__version__  # Tensorflow is pre-installed in google colab

'2.15.0'

# **Importing the dataset over here:**

In [3]:
data = pd.read_csv("Churn_Modelling.csv")
x = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values

**PRINT THE MATRIX OF FEATURES:**

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


# **Encoding the categorical data:**

**Label encoding of gender column:**

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [7]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


# **label encoding of categorical column:**

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# **Spliting the dataset into training set or test set:**

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)  # Random_state = 0 means every time generate the same output.

# **Feature scaling:**

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

-  # **PART - 2. BUILDING AN ARTIFICIAL NEURAL NETWORK:**

# **Initializing the ANN:**

In [12]:
ann = tf.keras.models.Sequential() # This code initializes a Sequential model in TensorFlow's Keras API, used for building neural networks layer by layer.

# **Adding the input layer and first hidden layer:**

In [13]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

# **Adding the second hiden input layer:**

In [14]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

# **Add the output layer:**

In [15]:
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

# **Part - 3. Training the ANN:**

# **Compiling the ANN:**

In [16]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy' ,metrics = ['accuracy'])

# **Training the ANN on the training set:**

In [17]:
ann.fit(x_train,y_train,batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7385
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4585 - accuracy: 0.8015
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4368 - accuracy: 0.8115
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4231 - accuracy: 0.8180
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4123 - accuracy: 0.8235
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4027 - accuracy: 0.8281
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3942 - accuracy: 0.8342
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3867 - accuracy: 0.8395
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3793 - accuracy: 0.8440
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3726 - accura

# **Part - 4. Making prediction and evaluation fo the model:**

In [18]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 [==============================] - 0s 195ms/step
[[False]]


# **Prediction the test set result:**

In [19]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# **Making the confusion matrix:**

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1533   62]
 [ 208  197]]


0.865