# This is all about the multi-linear Reggresion

<img src = "https://miro.medium.com/v2/resize:fit:638/1*-DWX3ZJaj0bvM1aPxcrtyA.jpeg" alt="MLR" height = "200" width = "470"  >

# 1.Importing the libraries -

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

# 2. Importing the dataset -

In [2]:
df = pd.read_csv("50_Startups.csv")

# 3. Extracting features X and Y 

In [3]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [4]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

# Checking the dataset is containg the null values or not -

In [5]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

# Why are we converting this categorical variable into the binary matrix?

# 4. Encoding the datasets - 

In [6]:
# Data Encoding - Data encoding means converting the categorical and test data into the numeric form / binary matrix and it is also called dummies variable
# with the help of pandas - 
# df = pd.get_dummies(df,columns=["State"],drop_first = True)

# # With the help of sklearn - 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[3])],remainder = "passthrough")
X = np.array(ct.fit_transform(X))

In [7]:
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

# 5. spliting the dataset into trainig set or test set - 

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 1/3,random_state = 0)

# 6. Traning the multiple linear regression model on the training set -

In [9]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

# 7. Now pridict the X_test set result - 

In [10]:
y_pred = regressor.predict(X_test)

In [11]:
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),axis = 1))

[[111616.64 103282.38]
 [132709.39 144259.4 ]
 [140155.11 146121.95]
 [ 76099.2   77798.83]
 [186329.94 191050.39]
 [112822.2  105008.31]
 [ 63002.    81229.06]
 [ 99107.1   97483.56]
 [119287.75 110352.25]
 [175522.84 166187.94]
 [101000.7   96778.92]
 [ 85772.99  96479.51]
 [117713.76 105733.54]
 [ 90230.88  96712.8 ]
 [133375.04 124266.9 ]
 [167530.55 155752.6 ]
 [158013.55 132602.65]]


In [12]:
y_train

array([ 64926.08,  35673.41, 101004.64, 129917.04,  99937.59,  97427.84,
       126992.93,  71498.49, 118474.03,  69758.98, 152211.77, 134307.35,
       107404.34, 156991.12, 125370.37,  78239.91,  14681.4 , 191792.06,
       141585.52,  89949.14, 108552.04, 156122.51, 108733.99,  90708.19,
       111313.02, 122776.86, 149759.96,  81005.76,  49490.75, 182901.99,
       192261.83,  42559.73,  65200.33])

In [13]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 , 155752.6 , 132602.65])